clean:
	mvn clean
	rm -rf jcstress.*
	rm -rf results/

run:
	java -XX:+UnlockDiagnosticVMOptions -XX:+WhiteBoxAPI -XX:-RestrictContended -Xbootclasspath/a:./ext-lib/jcstress-core.jar:./ext-lib/jopt-simple-4.9.jar:./target/CollisionTest.jar -jar target/CollisionTest.jar -v

.PHONY: clean run
